<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\EmployeeController;
use App\Http\Controllers\Admin\PositionController;
use App\Http\Controllers\Admin\StationController;
use App\Http\Controllers\Admin\UnitController;
use App\Http\Controllers\Admin\ItemsListController;
use App\Http\Controllers\Admin\SignatoryController;
use App\Http\Controllers\User\PpmpController;
use App\Http\Controllers\User\PpmpItemController;
use App\Http\Controllers\User\FundUtilizationController;
use App\Http\Controllers\User\FundUtilizationDetailsController;
use App\Http\Controllers\Supply\PpmpCheckController;
use App\Http\Controllers\Supply\PpmpItemCheckController;
use App\Http\Controllers\Supply\PoCheckController;
use App\Http\Controllers\Supply\PoItemCheckController;
use App\Http\Controllers\Budget\PpmpVerifyController;
use App\Http\Controllers\Budget\PpmpItemVerifyController;
use App\Http\Controllers\Sds\PpmpApproveController;
use App\Http\Controllers\Sds\PpmpItemApproveController;
use App\Http\Controllers\User\PrController;
use App\Http\Controllers\User\PrItemController;
use App\Http\Controllers\Supply\PrCheckController;
use App\Http\Controllers\Supply\PrItemCheckController;
use App\Http\Controllers\Budget\PrVerifyController;
use App\Http\Controllers\Budget\PrItemVerifyController;
use App\Http\Controllers\Budget\FundAllocationController;
use App\Http\Controllers\Budget\FundAllocationDetailsController;
use App\Http\Controllers\Budget\FundObligationController;
use App\Http\Controllers\Sds\PrApproveController;
use App\Http\Controllers\Sds\PrItemApproveController;
use App\Http\Controllers\Bac\SupplierController;
use App\Http\Controllers\Bac\FinalPpmpController;
use App\Http\Controllers\Bac\FinalPpmpItemController;
use App\Http\Controllers\Bac\FinalPrController;
use App\Http\Controllers\Bac\FinalPrItemController;
use App\Http\Controllers\Bac\PoController;
use App\Http\Controllers\Bac\PoItemController;
use App\Http\Controllers\Bac\RfqController;
use App\Http\Controllers\Bac\RfqItemController;
use App\Http\Controllers\Bac\AppController;
use App\Http\Controllers\Bac\AppItemController;
use App\Http\Controllers\Bac\AppCseController;
use App\Http\Controllers\Bac\AppNonCseController;

//PSMIS
use App\Http\Controllers\Supply\IarController;
use App\Http\Controllers\Supply\IarItemController;
use App\Http\Controllers\Supply\NodController;
use App\Http\Controllers\Supply\AssetController;
use App\Http\Controllers\Supply\AssetItemController;
use App\Http\Controllers\Supply\DonationController;
use App\Http\Controllers\Supply\DonationItemController;
use App\Http\Controllers\Supply\RisController;
use App\Http\Controllers\Supply\RisItemController;
use App\Http\Controllers\Supply\RsmiController;
use App\Http\Controllers\Supply\RsmiItemController;
use App\Http\Controllers\Supply\IcsHvController;
use App\Http\Controllers\Supply\IcsItemHvController;
use App\Http\Controllers\Supply\IcsLvController;
use App\Http\Controllers\Supply\IcsItemLvController;
use App\Http\Controllers\Supply\ParController;
use App\Http\Controllers\Supply\ParItemController;
use App\Http\Controllers\Supply\RrspHvController;
use App\Http\Controllers\Supply\RrspItemHvController;
use App\Http\Controllers\Supply\RrspLvController;
use App\Http\Controllers\Supply\RrspItemLvController;
use App\Http\Controllers\Supply\RspiHvController;
use App\Http\Controllers\Supply\RspiLvController;
use App\Http\Controllers\Supply\RppeiController;
use App\Http\Controllers\Supply\RrppeController;
use App\Http\Controllers\Supply\RrppeItemController;
use App\Http\Controllers\Supply\RegspiHvController;
use App\Http\Controllers\Supply\RegspiLvController;
use App\Http\Controllers\Supply\RegppeiController;
use App\Http\Controllers\Supply\StockController;
use App\Http\Controllers\Supply\StockCardController;
use App\Http\Controllers\Supply\SemiExpendableHvController;
use App\Http\Controllers\Supply\SemiExpendableCardHvController;
use App\Http\Controllers\Supply\SemiExpendableLvController;
use App\Http\Controllers\Supply\SemiExpendableCardLvController;
use App\Http\Controllers\Supply\PropertyController;
use App\Http\Controllers\Supply\PropertyCardController;
use App\Http\Controllers\Supply\SpLvRecipientController;
use App\Http\Controllers\Supply\SpHvRecipientController;
use App\Http\Controllers\Supply\PpeRecipientController;
use App\Http\Controllers\User\SpHvIssuedController;
use App\Http\Controllers\User\SpLvIssuedController;
use App\Http\Controllers\User\PpeIssuedController;

//Inventory
use App\Http\Controllers\Supply\RpcppeController;
use App\Http\Controllers\Supply\RpcspController;
use App\Http\Controllers\Supply\RpciController;
use App\Http\Controllers\Supply\IirupController;
use App\Http\Controllers\Supply\IirupItemController;
use App\Http\Controllers\Supply\IiruspController;
use App\Http\Controllers\Supply\IiruspItemController;

//Migration
use App\Http\Controllers\MigrationController;


Route::group(['prefix' => 'v1', 'as' => 'api.', 'namespace' => 'Admin'], function () {
    
    Route::get('/employeess', [EmployeeController::class, 'getEmployees'])->name('employee.index');
    Route::get('/position', [PositionController::class, 'getPositions'])->name('position.index');
    Route::get('/station', [StationController::class, 'getStations'])->name('station.index');
    Route::get('/unit', [UnitController::class, 'getUnits'])->name('unit.index');
    Route::get('/items_list', [ItemsListController::class, 'getItemsLists'])->name('items_list.index');
    Route::get('/signatory', [SignatoryController::class, 'getSignatories'])->name('signatory.index');
    Route::get('/fund_allocation', [FundAllocationController::class, 'getFunds'])->name('fund_allocation.index');
    Route::get('/fund_obligation', [FundObligationController::class, 'getFundObligations'])->name('fund_obligation.index');
    Route::get('/fund_utilization', [FundUtilizationController::class, 'getFundUtilizations'])->name('fund_utilization.index');
    Route::get('/fund_ppmp_details', [FundUtilizationDetailsController::class, 'getFundPpmps'])->name('fund_ppmp_details.index');
    Route::get('/fund_pr_details', [FundUtilizationDetailsController::class, 'getFundPurchaseRequests'])->name('fund_pr_details.index');
    Route::get('/fund_po_details', [FundUtilizationDetailsController::class, 'getFundPurchaseOrders'])->name('fund_po_details.index');
    Route::get('/fund_utilization_details', [FundUtilizationDetailsController::class, 'getUserFundObligations'])->name('fund_utilization_details.index');
    Route::get('/fund_allocation_ppmp_details', [FundAllocationDetailsController::class, 'getFundPpmps'])->name('fund_allocation_ppmp_details.index');
    Route::get('/fund_allocation_pr_details', [FundAllocationDetailsController::class, 'getFundPurchaseRequests'])->name('fund_allocation_pr_details.index');
    Route::get('/fund_allocation_po_details', [FundAllocationDetailsController::class, 'getFundPurchaseOrders'])->name('fund_allocation_po_details.index');
    Route::get('/fund_obligation_details', [FundAllocationDetailsController::class, 'getFundObligations'])->name('fund_obligation_details.index');
    Route::get('/ppmp', [PpmpController::class, 'getPpmps'])->name('ppmp.index');
    Route::get('/ppmp_item', [PpmpItemController::class, 'getPpmpItems'])->name('ppmp_item.index');
    Route::get('/ppmp_check', [PpmpCheckController::class, 'getPpmpCheck'])->name('ppmp_check.index');
    Route::get('/ppmp_checked', [PpmpCheckController::class, 'getPpmpChecked'])->name('ppmp_check.checked');
    Route::get('/ppmp_items_check', [PpmpItemCheckController::class, 'getPpmpItemsCheck'])->name('ppmp_item_check.index');
    Route::get('/ppmp_verify', [PpmpVerifyController::class, 'getPpmpVerify'])->name('ppmp_verify.index');
    Route::get('/ppmp_verified', [PpmpVerifyController::class, 'getPpmpVerified'])->name('ppmp_verify.verified');
    Route::get('/ppmp_item_verify', [PpmpItemVerifyController::class, 'getPpmpItemsVerify'])->name('ppmp_item_verify.index');
    Route::get('/ppmp_approve', [PpmpApproveController::class, 'getPpmpApprove'])->name('ppmp_approve.index');
    Route::get('/ppmp_item_approve', [PpmpItemApproveController::class, 'getPpmpItemsApprove'])->name('ppmp_item_approve.index');
    Route::get('/ppmp_final', [FinalPpmpController::class, 'getPpmpFinal'])->name('ppmp_final.index');
    Route::get('/ppmp_item_final', [FinalPpmpItemController::class, 'getPpmpItemFinal'])->name('ppmp_item_final.index');
    Route::get('/purchase_request', [PrController::class, 'getPurchaseRequests'])->name('purchase_request.index');
    Route::get('/purchase_request_item', [PrItemController::class, 'getPurchaseRequestItems'])->name('purchase_request_item.index');
    Route::get('/purchase_request_check', [PrCheckController::class, 'getPurchaseRequestCheck'])->name('purchase_request_check.index');
    Route::get('/purchase_request_checked', [PrCheckController::class, 'getPrChecked'])->name('purchase_request_check.checked');
    Route::get('/purchase_request_items_check', [PrItemCheckController::class, 'getPurchaseRequestItemsCheck'])->name('purchase_request_item_check.index');
    Route::get('/purchase_request_verify', [PrVerifyController::class, 'getPurchaseRequestVerify'])->name('purchase_request_verify.index');
    Route::get('/purchase_request_verified', [PrVerifyController::class, 'getPrVerified'])->name('purchase_request_verify.verified');
    Route::get('/purchase_request_items_verify', [PrItemVerifyController::class, 'getPurchaseRequestItemsVerify'])->name('purchase_request_item_verify.index');
    Route::get('/purchase_request_approve', [PrApproveController::class, 'getPurchaseRequestApprove'])->name('purchase_request_approve.index');
    Route::get('/purchase_request_items_approve', [PrItemApproveController::class, 'getPurchaseRequestItemsApprove'])->name('purchase_request_items_approve.index');
    Route::get('/purchase_request_final', [FinalPrController::class, 'getPurchaseRequestFinal'])->name('purchase_request_final.index');
    Route::get('/purchase_request_items_final', [FinalPrItemController::class, 'getPurchaseRequestItemsFinal'])->name('purchase_request_items_final.index');
    Route::get('/supplier', [SupplierController::class, 'getSuppliers'])->name('supplier.index');
    Route::get('/purchase_order', [PoController::class, 'getPurchaseOrders'])->name('purchase_order.index');
    Route::get('/purchase_order_check', [PoCheckController::class, 'getPurchaseOrderChecks'])->name('purchase_order_check.index');
    Route::get('/purchase_order_item', [PoItemController::class, 'getPurchaseOrderItems'])->name('purchase_order_item.index');
    Route::get('/purchase_order_item_check', [PoItemCheckController::class, 'getPurchaseOrderItemChecks'])->name('purchase_order_item_check.index');
    Route::get('/purchase_order_item_create', [PoItemController::class, 'getPurchaseRequestItems'])->name('purchase_order_item_create.index');
    Route::get('/request_for_quotation', [RfqController::class, 'getRequestForQuotations'])->name('request_for_quotation.index');
    Route::get('/request_for_quotation_item', [RfqItemController::class, 'getRequestForQuotationItems'])->name('request_for_quotation_item.index');
    Route::get('/app', [AppController::class, 'getApps'])->name('app.index');
    Route::get('/app_item', [AppItemController::class, 'getAppItems'])->name('app_item.index');
    Route::get('/app_cse', [AppCseController::class, 'getAppCses'])->name('app_cse.index');
    Route::get('/app_non_cse', [AppNonCseController::class, 'getAppNonCses'])->name('app_non_cse.index');

    //PSMIS
    Route::get('/iar', [IarController::class, 'getIars'])->name('iar.index');
    Route::get('/iar_item', [IarItemController::class, 'getIarItems'])->name('iar_item.index');    
    Route::get('/nod', [NodController::class, 'getNods'])->name('nod.index');
    Route::get('/asset', [AssetController::class, 'getAssets'])->name('asset.index');
    Route::get('/asset_item', [AssetItemController::class, 'getAssetItems'])->name('asset_item.index');
    Route::get('/donation', [DonationController::class, 'getDonations'])->name('donation.index');
    Route::get('/donation_item', [DonationItemController::class, 'getDonationItems'])->name('donation_item.index');    
    Route::get('/ris', [RisController::class, 'getRis'])->name('ris.index');
    Route::get('/ris_item', [RisItemController::class, 'getRisItems'])->name('ris_item.index');
    Route::get('/rsmi', [RsmiController::class, 'getRsmis'])->name('rsmi.index');
    Route::get('/rsmi_item', [RsmiItemController::class, 'getRsmiItems'])->name('rsmi_item.index');
    Route::get('/recap_rsmi_item', [RsmiItemController::class, 'getRecapItems'])->name('recap_rsmi_item.index');
    Route::get('/ics_hv', [IcsHvController::class, 'getIcsHv'])->name('ics_hv.index');
    Route::get('/ics_item_hv', [IcsItemHvController::class, 'getIcsItemHv'])->name('ics_item_hv.index');
    Route::get('/ics_lv', [IcsLvController::class, 'getIcsLv'])->name('ics_lv.index');
    Route::get('/ics_item_lv', [IcsItemLvController::class, 'getIcsItemLv'])->name('ics_item_lv.index');
    Route::get('/par', [ParController::class, 'getPars'])->name('par.index');
    Route::get('/par_item', [ParItemController::class, 'getParItems'])->name('par_item.index');
    Route::get('/rrsp_hv', [RrspHvController::class, 'getRrspHv'])->name('rrsp_hv.index');
    Route::get('/rrsp_item_hv', [RrspItemHvController::class, 'getRrspItemHv'])->name('rrsp_item_hv.index');
    Route::get('/rrsp_lv', [RrspLvController::class, 'getRrspLv'])->name('rrsp_lv.index');
    Route::get('/rrsp_item_lv', [RrspItemLvController::class, 'getRrspItemLv'])->name('rrsp_item_lv.index');
    Route::get('/rspi_hv', [RspiHvController::class, 'getRspiHv'])->name('rspi_hv.index');
    Route::get('/rspi_lv', [RspiLvController::class, 'getRspiLv'])->name('rspi_lv.index');
    Route::get('/rppei', [RppeiController::class, 'getRppei'])->name('rppei.index');
    Route::get('/rrppe', [RrppeController::class, 'getRrppe'])->name('rrppe.index');
    Route::get('/rrppe_item', [RrppeItemController::class, 'getRrppeItem'])->name('rrppe_item.index');
    Route::get('/regppei', [RegppeiController::class, 'getRegppei'])->name('regppei.index');
    Route::get('/regspi_hv', [RegspiHvController::class, 'getRegspiHv'])->name('regspi_hv.index');
    Route::get('/regspi_lv', [RegspiLvController::class, 'getRegspiLv'])->name('regspi_lv.index');
    Route::get('/stock', [StockController::class, 'getStocks'])->name('stock.index');
    Route::get('/stock_card', [StockCardController::class, 'getStockCards'])->name('stock_card.index');
    Route::get('/semi_expendable_hv', [SemiExpendableHvController::class, 'getSemiExpendableHvs'])->name('semi_expendable_hv.index');
    Route::get('/semi_expendable_card_hv', [SemiExpendableCardHvController::class, 'getSemiExpendableCardHvs'])->name('semi_expendable_card_hv.index');
    Route::get('/semi_expendable_lv', [SemiExpendableLvController::class, 'getSemiExpendableLvs'])->name('semi_expendable_lv.index');
    Route::get('/semi_expendable_card_lv', [SemiExpendableCardLvController::class, 'getSemiExpendableCardLvs'])->name('semi_expendable_card_lv.index');
    Route::get('/property', [PropertyController::class, 'getProperty'])->name('property.index');
    Route::get('/property_card', [PropertyCardController::class, 'getPropertyCards'])->name('property_card.index');
    Route::get('/semi_expendable_lv_recipient', [SpLvRecipientController::class, 'getSpLvRecipients'])->name('semi_expendable_lv_recipient.index');
    Route::get('/semi_expendable_lv_recipient_item', [SpLvRecipientController::class, 'getSpLvRecipientItems'])->name('semi_expendable_lv_recipient_item.index');
    Route::get('/semi_expendable_hv_recipient', [SpHvRecipientController::class, 'getSpHvRecipients'])->name('semi_expendable_hv_recipient.index');
    Route::get('/semi_expendable_hv_recipient_item', [SpHvRecipientController::class, 'getSpHvRecipientItems'])->name('semi_expendable_hv_recipient_item.index');
    Route::get('/ppe_recipient', [PpeRecipientController::class, 'getPpeRecipients'])->name('ppe_recipient.index');
    Route::get('/ppe_recipient_item', [PpeRecipientController::class, 'getPpeRecipientItems'])->name('ppe_recipient_item.index');
    Route::get('/semi_expendable_lv_received', [SpLvIssuedController::class, 'getSpLvIssuedItems'])->name('semi_expendable_lv_received.index');
    Route::get('/semi_expendable_hv_received', [SpHvIssuedController::class, 'getSpHvIssuedItems'])->name('semi_expendable_hv_received.index');
    Route::get('/ppe_received', [PpeIssuedController::class, 'getPpeIssuedItems'])->name('ppe_received.index');

    Route::get('/rpci', [RpciController::class, 'getRpci'])->name('rpci.index');
    Route::get('/rpcppe', [RpcppeController::class, 'getRpcppe'])->name('rpcppe.index');
    Route::get('/rpcsp', [RpcspController::class, 'getRpcsp'])->name('rpcsp.index');
    Route::get('/iirup', [IirupController::class, 'getIirups'])->name('iirup.index');
    Route::get('/iirup_item', [IirupItemController::class, 'getIirupItems'])->name('iirup_item.index');
    Route::get('/iirusp', [IiruspController::class, 'getIirusps'])->name('iirusp.index');
    Route::get('/iirusp_item', [IiruspItemController::class, 'getIiruspItems'])->name('iirusp_item.index');

    //Migration
    Route::get('/purchase_request_migration', [MigrationController::class, 'getMigratePurchaseRequests'])->name('purchase_request_migration.index');
    Route::get('/purchase_order_migration', [MigrationController::class, 'getMigratePurchaseOrders'])->name('purchase_order_migration.index');
    Route::get('/iar_migration', [MigrationController::class, 'getMigrateIars'])->name('iar_migration.index');

});
